/**
 * Gnim JS library v1.0.7
 * By Ming
 * http://gnim.net
 */
(function(o,f,I,g,n){function i(a,b){return a&&a._gnim?a:new r(a,b)}function r(a,b){this._gnim=!0;if(a!==g&&a!==n){var c;c=p(a)?"<"==a.charAt(0)?u(a):J(a,b):1===a.nodeType?[a]:q(a[d])?a:[a];this[d]=c[d];for(var e=0;e<c[d];e++)this[e]=c[e]}else this[d]=0}function J(a,b){b=b||f;p(b)?b=i(b):q(b[d])||(b=[b]);if(!b)return[];for(var c=/(#|\.|\s|^)(.*?)(#|\.|\s|$)/,e=[],s=a.split(","),j=0;j<s[d];j++){for(var l=[],g=b,n,h,v=s[j].replace(/^\s+|\s+$/g,"");""!=v;)for(var l=g,g=[],v=v.replace(c,function(a,b,
c,e){n=b;h=c;return e}).replace(/^\s+|\s+$/g,""),m=0;m<l[d];m++){var k=[];switch(n){case "#":k=K(h);break;case ".":k=L(h,l[m]);break;case "":k=M(h,l[m])}for(var o=0;o<k[d];o++)g.push(k[o])}for(l=0;l<g[d];l++)e.push(g[l])}return e}function K(a){return p(a)?(a=f.getElementById(a))?[a]:[]:[a]}function L(a,b){b=b||f;if(b.getElementsByClassName)return b.getElementsByClassName(a);for(var c=b.getElementsByTagName("*"),e=[],s=RegExp("(^|\\s)"+a+"(\\s|$)"),j=0;j<c[d];j++)s.test(c[j].className)&&e.push(c[j]);
return e}function M(a,b){b=b||f;return b.getElementsByTagName(a)}function A(a){return a.replace(/-(\w)/g,function(a,c){return c.toUpperCase()})}function p(a){return"string"==typeof a}function q(a){return"number"==typeof a}function w(a,b){for(var c in b)a[c]=b[c]}function B(a,b){for(var c=a.parentNode.childNodes,e=0;e<c[d];e++)if(c.item(e)===a&&e+1<c[d]){c=c.item(e+1);c.parentNode.insertBefore(b,c);return}a.parentNode.appendChild(b)}function x(a,b){return RegExp("(^|\\s)"+b+"(\\s|$)").test(a.className)?
!0:!1}function u(a){var b=[],c=f.createElement("div");for(c.innerHTML=a;c.firstChild;)b.push(c.firstChild),c.removeChild(c.firstChild);return b}function C(a,b){if(p(b))return"opacity"===b?D?a.style.filter&&0<=a.style.filter.indexOf("opacity=")?parseFloat(a.style.filter.match(/opacity=([^)]*)/)[1])/100:1:a.style.opacity?parseFloat(a.style.opacity):1:a.style[A(b)];for(var c in b)"opacity"==c?D?b[c]||"number"==typeof b[c]?(a.style.filter="alpha(opacity="+100*b[c]+");",a.style.zoom=1):(a.style.filter=
"",a.style.zoom=""):a.style.opacity=1==b[c]?"":b[c]:a.style[A(c)]=b[c]}function t(){for(E=!0;0!=y[d];)y.pop()()}function N(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return g}function z(a){var b=F,c=a.url?a.url:b.url,e=a.type?a.type.toUpperCase():b.type,d=a.contentType?a.contentType:b.contentType,j=a.dataType?a.dataType:b.dataType,l=a.success,f=a.error,b=a.timeout,a=a.data,i,h=N();if(!h)return h;
h.onreadystatechange=function(){if(4==h.readyState)if(i&&clearTimeout(i),200==h.status){if(l){var a=h.responseText;"text"==j?a=h.responseText:"json"==j?a=eval("("+h.responseText+")"):"xml"==j&&(a=h.responseXML);l(a)}}else 0!=h.status&&f&&f(h,h.status,"error")};q(b)&&(i=setTimeout(function(){h.abort();f&&f(g,g,"timeout")},b));"POST"==e?(h.open(e,c,!0),a&&h.setRequestHeader("Content-Type",d),h.send(G(a)||g)):(a&&(c+=(/\?/.test(c)?"&":"?")+G(a)),h.open(e,c,!0),h.send());return h}function G(a){var b=
[],c=/%20/g,e;for(e in a){var d=a[e]!=g?a[e].toString():g;d!==g&&d!==n&&(d=encodeURIComponent(e).replace(c,"+")+"="+encodeURIComponent(d).replace(c,"+"),b.push(d))}return b.join("&")}var d="length",m=function(a){var b=/(safari)[ \/]([\w.]+)/,c=/(webkit)[ \/]([\w.]+)/,e=/(opera)(?:.*version)?[ \/]([\w.]+)/,d=/(msie) ([\w.]+)/,j=/(firefox)[ \/]([\w.]+)/,g=/(mozilla)(?:.*? rv:([\w.]+))?/,a=/(chrome)[ \/]([\w.]+)/.exec(a)||b.exec(a)||c.exec(a)||e.exec(a)||d.exec(a)||j.exec(a)||g.exec(a)||[],b={};b[a[1]||
""]=!0;b.version=a[2]||0;return b}(o.navigator.userAgent.toLowerCase()),D=m.msie&&9>m.version,E=!1,y=[],k;f.addEventListener?(k=function(){f.removeEventListener("DOMContentLoaded",k,!1);t()},f.addEventListener("DOMContentLoaded",k,!1),o.addEventListener("load",t,!1)):f.attachEvent&&(k=function(){"complete"===f.readyState&&(f.detachEvent("onreadystatechange",k),t())},f.attachEvent("onreadystatechange",k),o.attachEvent("onload",t));var F={url:location.href,type:"GET",contentType:"application/x-www-form-urlencoded",
dataType:"text"};w(i,{broswer:m,ajaxSetting:F,core:r,ready:function(a){E?a():y.push(a)},isStr:p,isNum:q,isObj:function(a){return typeof a=="object"},isFunc:function(a){return typeof a=="function"},isArr:function(a){return a&&q(a[d])},isArray:function(a){return Object.prototype.toString.apply(a)==="[object Array]"},toStr:function(a){return""+a},toInt:function(a){return parseInt(a)},toFloat:function(a){return parseFloat(a)},toHex:function(a,b){var c="",b=b||0,a=parseInt(a),e=a<0;if(a==0){c="0";b--}else for(var a=
e?-a:a,d;a>0;){d=a%16;c=String.fromCharCode(d<10?48+d:97+d-10)+c;a=parseInt(a/16);b--}for(;b-- >0;)c="0"+c;return e?"-"+c:c},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},ltrim:function(a){return a.replace(/^\s+/g,"")},rtrim:function(a){return a.replace(/\s+$/g,"")},inject:w,build:u,noBubble:function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=true},noDefault:function(a){a.preventDefault?a.preventDefault():a.returnValue=false},now:function(){return(new Date).getTime()},log:function(a,
b){b===n?console&&console.log&&console.log(a):$('<div class="log">'+a+"</div>").appendTo(b);return a},ajax:z,post:function(a,b,c,d){return z({type:"POST",url:a,data:b,success:c,dataType:d})},get:function(a,b,c){return z({type:"GET",url:a,data:b,success:c})}});w(r.prototype,{each:function(a){for(var b=0;b<this[d];b++)a(this[b]);return this},find:function(a){return $(a,this)},html:function(a){if(a!==n){for(var b=0;b<this[d];b++)try{this[b].innerHTML=a}catch(c){for(var e=this[b];e.firstChild;)e.removeChild(e.firstChild);
a=u(a);for(e=0;e<a[d];e++)this[b].appendChild(a[e])}return this}return this[d]>0?this[0].innerHTML:g},text:function(a){if(a!==n){for(var b=0;b<this[d];b++)"innerText"in this[b]?this[b].innerText=a:this[b].textContent=a;return this}return this[d]>0?"innerText"in this[0]?this[0].innerText:this[0].textContent:g},append:function(a){if(this[d]>0)for(var a=i(a),b=0;b<a[d];b++)this[this[d]-1].appendChild(a[b]);return this},appendTo:function(a){a=i(a);if(a[d]>0)for(var b=0;b<this[d];b++)a[a[d]-1].appendChild(this[b]);
return this},prepend:function(a){if(this[d]>0)for(var a=i(a),b=0;b<a[d];b++){var c=this[this[d]-1],e=a[b];c.firstChild?c.insertBefore(e,c.firstChild):c.appendChild(e)}return this},prependTo:function(a){a=i(a);if(a[d]>0)for(var b=0;b<this[d];b++){var c=a[a[d]-1],e=this[b];c.firstChild?c.insertBefore(e,c.firstChild):c.appendChild(e)}return this},after:function(a){if(this[d]>0)for(var a=i(a),b=0;b<a[d];b++)B(this[this[d]-1],a[b]);return this},insertAfter:function(a){a=i(a);if(a[d]>0)for(var b=0;b<this[d];b++)B(a[a[d]-
1],this[b]);return this},before:function(a){if(this[d]>0)for(var a=i(a),b=0;b<a[d];b++){var c=this[this[d]-1];c.parentNode.insertBefore(a[b],c)}return this},insertBefore:function(a){a=i(a);if(a[d]>0)for(var b=0;b<this[d];b++){var c=a[a[d]-1];c.parentNode.insertBefore(this[b],c)}return this},remove:function(){for(var a=0;a<this[d];a++){var b=this[a];b.parentNode.removeChild(b)}return this},empty:function(){for(var a=0;a<this[d];a++)for(var b=this[a];b.firstChild;)b.removeChild(b.firstChild);return this},
css:function(a,b){var c={};if(b===n){if(p(a))return this[d]>0?C(this[0],a):g;c=a}else c[a]=b;for(var e=0;e<this[d];e++)C(this[e],c);return this},attr:function(a,b){var c={};if(b===n){if(p(a))return this[d]>0?this[0].getAttribute(a):g;c=a}else c[a]=b;for(var e=0;e<this[d];e++)for(var f in c)this[e].setAttribute(f,c[f]);return this},removeAttr:function(a){for(var b=0;b<this[d];b++)this[b].removeAttribute(a);return this},hasClass:function(a){return this[d]>0?x(this[0],a):false},addClass:function(a){for(var b=
0;b<this[d];b++){var c=this[b],e=a;if(!x(c,e))c.className=c.className+(" "+e)}return this},removeClass:function(a){for(var b=0;b<this[d];b++){var c=this[b];c.className=c.className.replace(RegExp("(^|\\s*)"+a+"(\\s*|$)")," ")}return this},toggleClass:function(a){for(var b=0;b<this[d];b++)this[b].className=x(this[b],a)?this[b].className.replace(RegExp("(^|\\s)"+a+"(\\s|$)"),""):this[b].className+(" "+a);return this},bind:function(a,b){for(var c=0;c<this[d];c++){var e=this[c],f=a,g=b;e.addEventListener?
e.addEventListener(f,g,false):e.attachEvent&&e.attachEvent("on"+f,g)}return this},unbind:function(a,b){for(var c=0;c<this[d];c++){var e=this[c],f=a,g=b;e.removeEventListener?e.removeEventListener(f,g,false):e.detachEvent&&e.detachEvent("on"+f,g)}return this},hover:function(a,b){return this.mouseover(a).mouseout(b||a)}});var m="blur,change,click,dblclick,error,focus,keydown,keypress,keyup,load,mousedown,mousemove,mouseout,mouseover,mouseup,resize,scroll,select,submit,unload".split(","),H;for(H in m)(function(a){r.prototype[a]=
function(b){return this.bind(a,b)}})(m[H]);I&&(o.$=i);o.Gnim=i})(window,document,!0,null);
