/*
 * Gnim JS library FX v0.3
 * By Ming
 * http://www.gnim.net
 */
(function(h,e,B){function o(a){return a.replace(/-(\w)/g,function(a,c){return c.toUpperCase()})}function w(a,b){var c=e,d;for(d in a)o(d)=="border"+b&&(c=a[d],delete a[d]);if(c)for(var g in x)a["border"+x[g]+b]=c}function y(a){a=o(a);return"color"==a||"backgroundColor"==a||"borderColor"==a||"borderLeftColor"==a||"borderRightColor"==a||"borderTopColor"==a||"borderBottomColor"==a}function z(a){var a=a.toLowerCase(),b=C.exec(a);if(b)return[k(b[1]),k(b[2]),k(b[3])];if(b=D.exec(a)||E.exec(a)){for(var a=
[],c=1;3>=c;c++)a.push(4==b.length?16*l[b[c]]+l[b[c]]:16*l[b[2*c-1]]+l[b[2*c]]);return a}return""}function F(a,b,c){return a+(b-a)*(-2*c*c+4*c)/2}function G(a,b,c){return a+(b-a)*c}function H(a,b,c){return a+(b-a)*(1-Math.sin(Math.PI*(0.5+c/2)))}function I(a,b,c){return a+1.1*(b-a)*Math.sin(2*c)}function J(){r==e&&(r=setInterval(function(){if(0==m.length)clearInterval(r),r=e;else for(var a=h.now(),b=0;b<m.length;b++){var c=m[b],d=a-c.b;if(d>=c.d)c.n.css(c.s),c.c&&c.c.apply(c.n[0]),m[b]=e,m.splice(b,
1),b--;else{for(var d=K(d)/c.d,g={},s=0;s<c.p.length;s++){var f=c.p[s],j=g,l=f.n;var p=c.t,q=d,n=void 0;if(h.isStr(f.s))f=f.s;else if(n="liner"==p?G:"sine"==p?H:"inertia"==p?I:F,y(f.n))var p=k(n(f.s.b[0],f.s.e[0],q)),o=k(n(f.s.b[1],f.s.e[1],q)),f=k(n(f.s.b[2],f.s.e[2],q)),f="#"+L(65536*p+256*o+f,6);else f="px"==f.s.u?k(n(f.s.b,f.s.e,q))+"px":n(f.s.b,f.s.e,q)+f.s.u;j[l]=f}c.n.css(g)}}},M))}function t(a,b){return"width"==b?a.offsetWidth+"px":"height"==b?a.offsetHeight+"px":"left"==b?a.offsetLeft+"px":
"right"==b?a.offsetLeft+a.offsetWidth+"px":"top"==b?a.offsetTop+"px":"bottom"==b?a.offsetTop+a.offsetHeight+"px":window.getComputedStyle?window.getComputedStyle(a,e)[b]:"opacity"==b&&h.broswer.msie?a.style.filter&&0<=a.style.filter.indexOf("opacity=")?parseFloat(a.style.filter.match(/opacity=([^)]*)/)[1])/100:1:a.currentStyle[o(b)]}function N(a,b,c){var d={};if("opacity"==a)return d.b=parseFloat(b),d.e=parseFloat(c),d.u="",d;if("display"==a)return"none"!=b?b:"none"!=c?c:b;if(y(a))return d.b=z(b),
d.e=z(c),d.u="",d.b&&d.e?d:c;a=/^(-?\d*)([a-zA-Z]*)$/;if(b)var g=b.match(a);if(c)var e=c.match(a);return g&&e&&g[2]==e[2]?(d.b=parseInt(g[1]),d.e=parseInt(e[1]),d.u=e[2],d):c}function A(a,b,c,d,g){w(b,"Color");w(b,"Width");var d={b:h.now(),d:c,n:h(a),p:[],s:b,c:d,t:g},e;for(e in b)g={},g.n=e,g.s=N(e,t(a,e),b[e]),d.p.push(g);c===B?d.d=500:"fast"===c?d.d=200:"slow"===c&&(d.d=1E3);m.push(d);J()}function u(a){var b=a.offsetLeft;a.offsetParent!=e&&(b+=u(a.offsetParent));return b}function v(a){var b=a.offsetTop;
a.offsetParent!=e&&(b+=v(a.offsetParent));return b}for(var m=[],r=e,M=20,k=h.toInt,K=h.toFloat,L=h.toHex,x=["Left","Right","Top","Bottom"],C=/^rgb\(\s*(\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,D=/^#([0-9a-f])([0-9a-f])([0-9a-f])$/,E=/^#([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])$/,l={a:10,b:11,c:12,d:13,e:14,f:15},j=0;9>=j;j++)l[j]=j;j={currentStyle:function(a,b){var c=h(a);return 0<c.length?t(c[0],b):e},anim:function(a,b,c,d,e){a=h(a);return 0<a.length?(A(a[i],b,c,d,e),!0):!1}};j.left=
u;j.top=v;j.width=function(a){return a.offsetWidth};j.height=function(a){return a.offsetHeight};h.fx=j;h.inject(h.core.prototype,{currentStyle:function(a){return 0<this.length?t(this[0],a):e},anim:function(a,b,c,d){for(var e=0;e<this.length;e++)A(this[e],a,b,c,d);return this},left:function(){return 0<this.length?u(this[0]):e},top:function(){return 0<this.length?v(this[0]):e},width:function(){return 0<this.length?this[0].offsetWidth:e},height:function(){return 0<this.length?this[0].offsetHeight:e}})})(Gnim,
null);