/**
 * Gnim JS library v1.0.7
 * By Ming
 * http://gnim.net
 */
(function(s,j,L,n){function k(a,b){return a&&a._gnim?a:new v(a,b)}function v(a,b){this._gnim=true;if(a!==null&&a!==n){var c;c=o(a)?a.charAt(0)=="<"?y(a):M(a,b):a.nodeType===1?[a]:t(a[e])?a:[a];this[e]=c[e];for(var d=0;d<c[e];d++)this[d]=c[d]}else this[e]=0}function M(a,b){b=b||j;b=o(b)?k(b):t(b[e])?b:[b];if(!b)return[];for(var c=/(#|\.|\s|^)(.*?)(#|\.|\s|$)/,d=[],g=a.split(","),h=0;h<g[e];h++){for(var i=[],l=b,p,f,m=g[h].replace(/^\s+|\s+$/g,"");m!="";){i=l;l=[];m=m.replace(c,function(V,N,O,P){p=
N;f=O;return P}).replace(/^\s+|\s+$/g,"");for(var w=0;w<i[e];w++){var u=[];switch(p){case "#":u=Q(f);break;case ".":u=R(f,i[w]);break;case "":u=S(f,i[w]);break}for(var z=0;z<u[e];z++)l.push(u[z])}}for(i=0;i<l[e];i++)d.push(l[i])}return d}function Q(a){if(o(a))return(a=j.getElementById(a))?[a]:[];return[a]}function R(a,b){b=b||j;if(b.getElementsByClassName)return b.getElementsByClassName(a);for(var c=b.getElementsByTagName("*"),d=[],g=new RegExp("(^|\\s)"+a+"(\\s|$)"),h=0;h<c[e];h++)g.test(c[h].className)&&
d.push(c[h]);return d}function S(a,b){b=b||j;return b.getElementsByTagName(a)}function E(a){return a.replace(/-(\w)/g,function(b,c){return c.toUpperCase()})}function o(a){return typeof a=="string"}function t(a){return typeof a=="number"}function A(a,b){for(var c in b)a[c]=b[c]}function F(a,b){for(var c=a.parentNode.childNodes,d=0;d<c[e];d++)if(c.item(d)===a&&d+1<c[e]){c=c.item(d+1);c.parentNode.insertBefore(b,c);return}a.parentNode.appendChild(b)}function B(a,b){if((new RegExp("(^|\\s)"+b+"(\\s|$)")).test(a.className))return true;
return false}function y(a){var b=[],c=j.createElement("div");for(c.innerHTML=a;c.firstChild;){b.push(c.firstChild);c.removeChild(c.firstChild)}return b}function G(a,b){if(o(b)){if(b==="opacity")return H?a.style.filter&&a.style.filter.indexOf("opacity=")>=0?parseFloat(a.style.filter.match(/opacity=([^)]*)/)[1])/100:1:a.style.opacity?parseFloat(a.style.opacity):1;return a.style[E(b)]}else for(var c in b)if(c=="opacity")if(H)if(b[c]||typeof b[c]=="number"){a.style.filter="alpha(opacity="+b[c]*100+");";
a.style.zoom=1}else{a.style.filter="";a.style.zoom=""}else a.style.opacity=b[c]==1?"":b[c];else a.style[E(c)]=b[c]}function x(){for(I=true;C[e]!=0;)C.pop()()}function T(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return null}function D(a){var b=J,c=a.url?a.url:b.url,d=a.type?a.type.toUpperCase():b.type,g=a.contentType?a.contentType:b.contentType,h=a.dataType?a.dataType:b.dataType,i=a.success,
l=a.error;b=a.timeout;a=a.data;var p,f=T();if(!f)return f;f.onreadystatechange=function(){if(f.readyState==4){p&&clearTimeout(p);if(f.status==200){if(i){var m=f.responseText;if(h=="text")m=f.responseText;else if(h=="json")m=eval("("+f.responseText+")");else if(h=="xml")m=f.responseXML;i(m)}}else f.status!=0&&l&&l(f,f.status,"error")}};if(t(b))p=setTimeout(function(){f.abort();l&&l(null,null,"timeout")},b);if(d=="POST"){f.open(d,c,true);a&&f.setRequestHeader("Content-Type",g);f.send(K(a)||null)}else{if(a)c+=
(/\?/.test(c)?"&":"?")+K(a);f.open(d,c,true);f.send()}return f}function K(a){var b=[],c=/%20/g;for(var d in a){var g=a[d]!=null?a[d].toString():null;if(g!==null&&g!==n){g=encodeURIComponent(d).replace(c,"+")+"="+encodeURIComponent(g).replace(c,"+");b.push(g)}}return b.join("&")}var e="length",q=function(a){var b=/(safari)[ \/]([\w.]+)/,c=/(webkit)[ \/]([\w.]+)/,d=/(opera)(?:.*version)?[ \/]([\w.]+)/,g=/(msie) ([\w.]+)/,h=/(firefox)[ \/]([\w.]+)/,i=/(mozilla)(?:.*? rv:([\w.]+))?/;a=/(chrome)[ \/]([\w.]+)/.exec(a)||
b.exec(a)||c.exec(a)||d.exec(a)||g.exec(a)||h.exec(a)||i.exec(a)||[];b={};b[a[1]||""]=true;b.version=a[2]||0;return b}(s.navigator.userAgent.toLowerCase()),H=q.msie&&q.version<9,I=false,C=[],r;if(j.addEventListener){r=function(){j.removeEventListener("DOMContentLoaded",r,false);x()};j.addEventListener("DOMContentLoaded",r,false);s.addEventListener("load",x,false)}else if(j.attachEvent){r=function(){if(j.readyState==="complete"){j.detachEvent("onreadystatechange",r);x()}};j.attachEvent("onreadystatechange",
r);s.attachEvent("onload",x)}var J={url:location.href,type:"GET",contentType:"application/x-www-form-urlencoded",dataType:"text"};A(k,{broswer:q,ajaxSetting:J,core:v,ready:function(a){I?a():C.push(a)},isStr:o,isNum:t,isObj:function(a){return typeof a=="object"},isFunc:function(a){return typeof a=="function"},isArr:function(a){return a&&t(a[e])},isArray:function(a){return Object.prototype.toString.apply(a)==="[object Array]"},toStr:function(a){return""+a},toInt:function(a){return parseInt(a)},toFloat:function(a){return parseFloat(a)},
toHex:function(a,b){var c="";b=b||0;a=parseInt(a);var d=a<0;if(a==0){c="0";b--}else{a=d?-a:a;for(var g;a>0;){g=a%16;c=String.fromCharCode(g<10?48+g:97+g-10)+c;a=parseInt(a/16);b--}}for(;b-- >0;)c="0"+c;return d?"-"+c:c},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},ltrim:function(a){return a.replace(/^\s+/g,"")},rtrim:function(a){return a.replace(/\s+$/g,"")},inject:A,build:y,noBubble:function(a){if(a.stopPropagation)a.stopPropagation();else a.cancelBubble=true},noDefault:function(a){if(a.preventDefault)a.preventDefault();
else a.returnValue=false},now:function(){return(new Date).getTime()},log:function(a,b){if(b===n)console&&console.log&&console.log(a);else $('<div class="log">'+a+"</div>").appendTo(b);return a},ajax:D,post:function(a,b,c,d){return D({type:"POST",url:a,data:b,success:c,dataType:d})},get:function(a,b,c){return D({type:"GET",url:a,data:b,success:c})}});A(v.prototype,{each:function(a){for(var b=0;b<this[e];b++)a(this[b]);return this},find:function(a){return $(a,this)},html:function(a){if(a!==n){for(var b=
0;b<this[e];b++)try{this[b].innerHTML=a}catch(c){for(var d=this[b];d.firstChild;)d.removeChild(d.firstChild);a=y(a);for(d=0;d<a[e];d++)this[b].appendChild(a[d])}return this}else return this[e]>0?this[0].innerHTML:null},text:function(a){if(a!==n){for(var b=0;b<this[e];b++)if("innerText"in this[b])this[b].innerText=a;else this[b].textContent=a;return this}else return this[e]>0?"innerText"in this[0]?this[0].innerText:this[0].textContent:null},append:function(a){if(this[e]>0){a=k(a);for(var b=0;b<a[e];b++)this[this[e]-
1].appendChild(a[b])}return this},appendTo:function(a){a=k(a);if(a[e]>0)for(var b=0;b<this[e];b++)a[a[e]-1].appendChild(this[b]);return this},prepend:function(a){if(this[e]>0){a=k(a);for(var b=0;b<a[e];b++){var c=this[this[e]-1],d=a[b];c.firstChild?c.insertBefore(d,c.firstChild):c.appendChild(d)}}return this},prependTo:function(a){a=k(a);if(a[e]>0)for(var b=0;b<this[e];b++){var c=a[a[e]-1],d=this[b];c.firstChild?c.insertBefore(d,c.firstChild):c.appendChild(d)}return this},after:function(a){if(this[e]>
0){a=k(a);for(var b=0;b<a[e];b++)F(this[this[e]-1],a[b])}return this},insertAfter:function(a){a=k(a);if(a[e]>0)for(var b=0;b<this[e];b++)F(a[a[e]-1],this[b]);return this},before:function(a){if(this[e]>0){a=k(a);for(var b=0;b<a[e];b++){var c=this[this[e]-1];c.parentNode.insertBefore(a[b],c)}}return this},insertBefore:function(a){a=k(a);if(a[e]>0)for(var b=0;b<this[e];b++){var c=a[a[e]-1];c.parentNode.insertBefore(this[b],c)}return this},remove:function(){for(var a=0;a<this[e];a++){var b=this[a];b.parentNode.removeChild(b)}return this},
empty:function(){for(var a=0;a<this[e];a++)for(var b=this[a];b.firstChild;)b.removeChild(b.firstChild);return this},css:function(a,b){var c={};if(b===n)if(o(a))return this[e]>0?G(this[0],a):null;else c=a;else c[a]=b;for(var d=0;d<this[e];d++)G(this[d],c);return this},attr:function(a,b){var c={};if(b===n)if(o(a))return this[e]>0?this[0].getAttribute(a):null;else c=a;else c[a]=b;for(var d=0;d<this[e];d++)for(var g in c)this[d].setAttribute(g,c[g]);return this},removeAttr:function(a){for(var b=0;b<this[e];b++)this[b].removeAttribute(a);
return this},hasClass:function(a){return this[e]>0?B(this[0],a):false},addClass:function(a){for(var b=0;b<this[e];b++){var c=this[b];B(c,a)||(c.className+=" "+a)}return this},removeClass:function(a){for(var b=0;b<this[e];b++){var c=this[b];c.className=c.className.replace(new RegExp("(^|\\s*)"+a+"(\\s*|$)")," ")}return this},toggleClass:function(a){for(var b=0;b<this[e];b++)if(B(this[b],a))this[b].className=this[b].className.replace(new RegExp("(^|\\s)"+a+"(\\s|$)"),"");else this[b].className+=" "+
a;return this},bind:function(a,b){for(var c=0;c<this[e];c++){var d=this[c];if(d.addEventListener)d.addEventListener(a,b,false);else d.attachEvent&&d.attachEvent("on"+a,b)}return this},unbind:function(a,b){for(var c=0;c<this[e];c++){var d=this[c];if(d.removeEventListener)d.removeEventListener(a,b,false);else d.detachEvent&&d.detachEvent("on"+a,b)}return this},hover:function(a,b){return this.mouseover(a).mouseout(b||a)}});q=["blur","change","click","dblclick","error","focus","keydown","keypress","keyup",
"load","mousedown","mousemove","mouseout","mouseover","mouseup","resize","scroll","select","submit","unload"];for(var U in q)(function(a){v.prototype[a]=function(b){return this.bind(a,b)}})(q[U]);if(L)s.$=k;s.Gnim=k})(window,document,true);
