/*
 * Gnim JS library FX v0.3
 * By Ming
 * http://www.gnim.net
 */
(function(g,A){function r(a){return a.replace(/-(\w)/g,function(b,c){return c.toUpperCase()})}function v(a,b){var c=null;for(var d in a)if(r(d)=="border"+b){c=a[d];delete a[d]}if(c)for(var f in w)a["border"+w[f]+b]=c}function x(a){a=r(a);return a=="color"||a=="backgroundColor"||a=="borderColor"||a=="borderLeftColor"||a=="borderRightColor"||a=="borderTopColor"||a=="borderBottomColor"}function y(a){a=a.toLowerCase();var b=B.exec(a);if(b)return[k(b[1]),k(b[2]),k(b[3])];if(b=C.exec(a)||D.exec(a)){a=[];
for(var c=1;c<=3;c++)a.push(b.length==4?o[b[c]]*16+o[b[c]]:o[b[2*c-1]]*16+o[b[2*c]]);return a}return""}function E(a,b,c){return a+(b-a)*(-2*c*c+c*4)/2}function F(a,b,c){return a+(b-a)*c}function G(a,b,c){return a+(b-a)*(1-Math.sin(Math.PI*(0.5+c/2)))}function H(a,b,c){return a+(b-a)*1.1*Math.sin(c*2)}function I(){if(q==null)q=setInterval(function(){if(m.length==0){clearInterval(q);q=null}else for(var a=g.now(),b=0;b<m.length;b++){var c=m[b],d=a-c.b;if(d>=c.d){c.n.css(c.s);c.c&&c.c.apply(c.n[0]);m[b]=
null;m.splice(b,1);b--}else{d=J(d)/c.d;for(var f={},h=0;h<c.p.length;h++){var e=c.p[h],K=e.n;var p=c.t,n=void 0;if(g.isStr(e.s))e=e.s;else{n=p=="liner"?F:p=="sine"?G:p=="inertia"?H:E;if(x(e.n)){p=k(n(e.s.b[0],e.s.e[0],d));var L=k(n(e.s.b[1],e.s.e[1],d));e=k(n(e.s.b[2],e.s.e[2],d));e="#"+M(p*256*256+L*256+e,6)}else e=e.s.u=="px"?k(n(e.s.b,e.s.e,d))+"px":n(e.s.b,e.s.e,d)+e.s.u}f[K]=e}c.n.css(f)}}},N)}function s(a,b){if(b=="width")return a.offsetWidth+"px";if(b=="height")return a.offsetHeight+"px";if(b==
"left")return a.offsetLeft+"px";if(b=="right")return a.offsetLeft+a.offsetWidth+"px";if(b=="top")return a.offsetTop+"px";if(b=="bottom")return a.offsetTop+a.offsetHeight+"px";if(window.getComputedStyle)return window.getComputedStyle(a,null)[b];if(b=="opacity"&&g.broswer.msie)return a.style.filter&&a.style.filter.indexOf("opacity=")>=0?parseFloat(a.style.filter.match(/opacity=([^)]*)/)[1])/100:1;return a.currentStyle[r(b)]}function O(a,b,c){var d={};if(a=="opacity"){d.b=parseFloat(b);d.e=parseFloat(c);
d.u="";return d}else if(a=="display"){if(b!="none")return b;if(c!="none")return c;return b}else if(x(a)){d.b=y(b);d.e=y(c);d.u="";return d.b&&d.e?d:c}else{a=/^(\d*)([a-zA-Z]*)$/;if(b)var f=b.match(a);if(c)var h=c.match(a);if(f&&h&&f[2]==h[2]){d.b=parseInt(f[1]);d.e=parseInt(h[1]);d.u=h[2];return d}return c}}function z(a,b,c,d,f){v(b,"Color");v(b,"Width");d={b:g.now(),d:c,n:g(a),p:[],s:b,c:d,t:f};for(var h in b){f={};f.n=h;f.s=O(h,s(a,h),b[h]);d.p.push(f)}if(c===A)d.d=500;else if(c==="fast")d.d=200;
else if(c==="slow")d.d=1E3;m.push(d);I()}function t(a){var b=a.offsetLeft;if(a.offsetParent!=null)b+=t(a.offsetParent);return b}function u(a){var b=a.offsetTop;if(a.offsetParent!=null)b+=u(a.offsetParent);return b}for(var m=[],q=null,N=20,k=g.toInt,J=g.toFloat,M=g.toHex,w=["Left","Right","Top","Bottom"],B=/^rgb\(\s*(\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,C=/^#([0-9a-f])([0-9a-f])([0-9a-f])$/,D=/^#([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])$/,o={a:10,b:11,c:12,d:13,e:14,f:15},j=0;j<=
9;j++)o[j]=j;j={};j.currentStyle=function(a,b){var c=g(a);if(c.length>0)return s(c[0],b);return null};j.anim=function(a,b,c,d,f){a=g(a);if(a.length>0){z(a[i],b,c,d,f);return true}return false};j.left=t;j.top=u;j.width=function(a){return a.offsetWidth};j.height=function(a){return a.offsetHeight};var l={};l.currentStyle=function(a){if(this.length>0)return s(this[0],a);return null};l.anim=function(a,b,c,d){for(var f=0;f<this.length;f++)z(this[f],a,b,c,d);return this};l.left=function(){if(this.length>
0)return t(this[0]);return null};l.top=function(){if(this.length>0)return u(this[0]);return null};l.width=function(){if(this.length>0)return this[0].offsetWidth;return null};l.height=function(){if(this.length>0)return this[0].offsetHeight;return null};g.fx=j;g.inject(g.core.prototype,l)})(Gnim);
